"""crcd

Revision ID: 1ea9757f55f6
Revises: 4121808fbb14
Create Date: 2022-05-30 09:25:27.900736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea9757f55f6'
down_revision = '4121808fbb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_role_Id'), 'shop_role', ['Id'], unique=False)
    op.add_column('shop', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shop', 'shop_role', ['role_id'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.drop_column('shop', 'role_id')
    op.drop_index(op.f('ix_shop_role_Id'), table_name='shop_role')
    op.drop_table('shop_role')
    # ### end Alembic commands ###
