"""create account table

Revision ID: 22d7a2bd5017
Revises: f4fcb7e2902a
Create Date: 2022-05-15 01:11:44.019098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d7a2bd5017'
down_revision = 'f4fcb7e2902a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
