"""create account table

Revision ID: 2aefa6c30647
Revises: 
Create Date: 2022-05-14 18:30:29.221672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aefa6c30647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Appuser',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('HashedPassword', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=255), nullable=True),
    sa.Column('FullName', sa.String(length=255), nullable=True),
    sa.Column('ProfileImage', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsConfirmed', sa.Boolean(), nullable=False),
    sa.Column('LastPasswordReset', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Appuser_Email'), 'Appuser', ['Email'], unique=True)
    op.create_index(op.f('ix_Appuser_Id'), 'Appuser', ['Id'], unique=False)
    op.create_index(op.f('ix_Appuser_Username'), 'Appuser', ['Username'], unique=True)
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Roles_Id'), 'Roles', ['Id'], unique=False)
    op.create_table('UserRole',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Roles.Id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Appuser.Id'], ),
    sa.PrimaryKeyConstraint('userId', 'roleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRole')
    op.drop_index(op.f('ix_Roles_Id'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Appuser_Username'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Id'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Email'), table_name='Appuser')
    op.drop_table('Appuser')
    # ### end Alembic commands ###
