"""crcd

Revision ID: 4121808fbb14
Revises: b2ebd2768cde
Create Date: 2022-05-30 09:23:09.106366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4121808fbb14'
down_revision = 'b2ebd2768cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'shop', ['shop_id'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'shop_id')
    # ### end Alembic commands ###
