"""last3

Revision ID: 43246bc9614b
Revises: 
Create Date: 2022-05-31 06:06:50.048477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43246bc9614b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_offer_Id'), 'offer', ['Id'], unique=False)
    op.create_table('offer_item',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.Id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_offer_item_Id'), 'offer_item', ['Id'], unique=False)
    op.create_table('wishlist',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_wishlist_Id'), 'wishlist', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_Id'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_offer_item_Id'), table_name='offer_item')
    op.drop_table('offer_item')
    op.drop_index(op.f('ix_offer_Id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
