"""create account table

Revision ID: 438c65b7543e
Revises: cea972698d68
Create Date: 2022-04-13 07:43:08.831202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438c65b7543e'
down_revision = 'cea972698d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
