"""create account table

Revision ID: 4ad7ce46d6f0
Revises: 
Create Date: 2022-04-23 19:34:40.348867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '4ad7ce46d6f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Item_Id'), 'Item', ['Id'], unique=False)
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Roles_Id'), 'Roles', ['Id'], unique=False)
    op.create_table('Appuser',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('HashedPassword', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(), nullable=True),
    sa.Column('ProfileImage', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('RoleId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Appuser_Email'), 'Appuser', ['Email'], unique=True)
    op.create_index(op.f('ix_Appuser_Id'), 'Appuser', ['Id'], unique=False)
    op.create_index(op.f('ix_Appuser_Username'), 'Appuser', ['Username'], unique=True)
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('completed', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__notes__3213E83FE31384E3')
    )
    op.drop_index(op.f('ix_Appuser_Username'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Id'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Email'), table_name='Appuser')
    op.drop_table('Appuser')
    op.drop_index(op.f('ix_Roles_Id'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Item_Id'), table_name='Item')
    op.drop_table('Item')
    # ### end Alembic commands ###
