"""create account table

Revision ID: 66ac36091014
Revises: 65b45ab14a20
Create Date: 2022-05-05 02:39:20.905471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ac36091014'
down_revision = '65b45ab14a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appuser', sa.Column('FullName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Appuser', 'FullName')
    # ### end Alembic commands ###
