"""create account table

Revision ID: 7890c22ee733
Revises: c2afe33c0550
Create Date: 2022-03-26 15:15:35.514415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7890c22ee733'
down_revision = 'c2afe33c0550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Roles_Id'), 'Roles', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Roles_Id'), table_name='Roles')
    op.drop_table('Roles')
    # ### end Alembic commands ###
