"""create account table

Revision ID: a1bcf08f0d55
Revises: 07888ad20be5
Create Date: 2022-04-02 07:47:00.577924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bcf08f0d55'
down_revision = '07888ad20be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
