"""create account table

Revision ID: a77d6ad21a6e
Revises: 2aefa6c30647
Create Date: 2022-05-15 01:01:57.737988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77d6ad21a6e'
down_revision = '2aefa6c30647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
