"""crcd

Revision ID: b2ebd2768cde
Revises: d708cb103aaa
Create Date: 2022-05-30 09:20:58.230634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ebd2768cde'
down_revision = 'd708cb103aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_Id'), 'shop', ['Id'], unique=False)
    op.create_table('user_shop',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_shop')
    op.drop_index(op.f('ix_shop_Id'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
