"""create account table

Revision ID: bceca5c0b7a6
Revises: 22d7a2bd5017
Create Date: 2022-05-15 01:13:08.981495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceca5c0b7a6'
down_revision = '22d7a2bd5017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Appuser', 'LastPasswordReset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appuser', sa.Column('LastPasswordReset', sa.DATETIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
