"""create account table

Revision ID: cea972698d68
Revises: a1bcf08f0d55
Create Date: 2022-04-13 07:36:14.767522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea972698d68'
down_revision = 'a1bcf08f0d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
