"""create account table

Revision ID: e8d25133f913
Revises: ef93f2b2d47b
Create Date: 2022-05-18 15:05:48.200008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e8d25133f913'
down_revision = 'ef93f2b2d47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_password_reset', sa.REAL(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_app_user_Id'), 'app_user', ['Id'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_role_Id'), 'role', ['Id'], unique=False)
    op.create_table('shop',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_Id'), 'shop', ['Id'], unique=False)
    op.create_table('shop_role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_role_Id'), 'shop_role', ['Id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_shop',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['shop_role.Id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id', 'role_id')
    )
    op.drop_index('ix_Roles_Id', table_name='Roles')
    op.drop_table('Roles')
    op.drop_index('ix_Appuser_Id', table_name='Appuser')
    op.drop_table('Appuser')
    op.drop_table('UserRole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRole',
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Roles.Id'], name='FK__UserRole__roleId__30C33EC3'),
    sa.ForeignKeyConstraint(['userId'], ['Appuser.Id'], name='FK__UserRole__userId__31B762FC'),
    sa.PrimaryKeyConstraint('userId', 'roleId', name='PK__UserRole__7743989DA1BC252F')
    )
    op.create_table('Appuser',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('HashedPassword', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PhoneNumber', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FullName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ProfileImage', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IsActive', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('IsConfirmed', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('LastPasswordReset', mssql.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__Appuser__3214EC079034A904')
    )
    op.create_index('ix_Appuser_Id', 'Appuser', ['Id'], unique=False)
    op.create_table('Roles',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK__Roles__3214EC071C8D3D41')
    )
    op.create_index('ix_Roles_Id', 'Roles', ['Id'], unique=False)
    op.drop_table('user_shop')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_shop_role_Id'), table_name='shop_role')
    op.drop_table('shop_role')
    op.drop_index(op.f('ix_shop_Id'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_role_Id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_Id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
