"""last4

Revision ID: e91e13903cf3
Revises: 43246bc9614b
Create Date: 2022-05-31 06:23:05.332674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91e13903cf3'
down_revision = '43246bc9614b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_category', sa.Column('name_en', sa.String(length=255), nullable=True))
    op.add_column('item_category', sa.Column('describe_en', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_category', 'describe_en')
    op.drop_column('item_category', 'name_en')
    # ### end Alembic commands ###
