"""create account table

Revision ID: ef93f2b2d47b
Revises: bceca5c0b7a6
Create Date: 2022-05-15 01:19:41.075175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef93f2b2d47b'
down_revision = 'bceca5c0b7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appuser', sa.Column('LastPasswordReset', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Appuser', 'LastPasswordReset')
    # ### end Alembic commands ###
