"""create account table

Revision ID: f4853a1ad15b
Revises: 
Create Date: 2022-05-19 01:38:40.454202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4853a1ad15b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_password_reset', sa.REAL(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_app_user_Id'), 'app_user', ['Id'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_role_Id'), 'role', ['Id'], unique=False)
    op.create_table('shop',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_Id'), 'shop', ['Id'], unique=False)
    op.create_table('shop_role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_shop_role_Id'), 'shop_role', ['Id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_shop',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['shop_role.Id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_shop')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_shop_role_Id'), table_name='shop_role')
    op.drop_table('shop_role')
    op.drop_index(op.f('ix_shop_Id'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_role_Id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_Id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
