"""omarx

Revision ID: 22b4f6860772
Revises: cb77e0b54e6c
Create Date: 2022-03-14 15:31:09.578182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b4f6860772'
down_revision = 'cb77e0b54e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
