"""create account table

Revision ID: 782f763784fd
Revises: f70036b8e1c6
Create Date: 2022-03-16 16:13:55.541388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782f763784fd'
down_revision = 'f70036b8e1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
