"""omarx

Revision ID: e82ead0606bc
Revises: 67452e124632
Create Date: 2022-03-14 15:28:58.658269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82ead0606bc'
down_revision = '67452e124632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PhoneNumberx', sa.String(), nullable=True))
    op.drop_column('users', 'PhoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PhoneNumber', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('users', 'PhoneNumberx')
    # ### end Alembic commands ###
