"""omar

Revision ID: eae020e49749
Revises: 
Create Date: 2022-03-14 15:27:05.442994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae020e49749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('HashedPassword', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(), nullable=True),
    sa.Column('ProfileImage', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Id'), 'users', ['Id'], unique=False)
    op.create_index(op.f('ix_users_Username'), 'users', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_Username'), table_name='users')
    op.drop_index(op.f('ix_users_Id'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
