"""omar

Revision ID: f70036b8e1c6
Revises: 22b4f6860772
Create Date: 2022-03-15 15:59:01.260987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70036b8e1c6'
down_revision = '22b4f6860772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PhoneNumber', sa.String(), nullable=True))
    op.drop_column('users', 'PhoneNumberx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PhoneNumberx', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('users', 'PhoneNumber')
    # ### end Alembic commands ###
