"""omar32142

Revision ID: 513f6b9481e1
Revises: 
Create Date: 2022-03-17 09:59:08.349637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513f6b9481e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Appuser',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('HashedPassword', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(), nullable=True),
    sa.Column('ProfileImage', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Appuser_Email'), 'Appuser', ['Email'], unique=True)
    op.create_index(op.f('ix_Appuser_Id'), 'Appuser', ['Id'], unique=False)
    op.create_index(op.f('ix_Appuser_Username'), 'Appuser', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Appuser_Username'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Id'), table_name='Appuser')
    op.drop_index(op.f('ix_Appuser_Email'), table_name='Appuser')
    op.drop_table('Appuser')
    # ### end Alembic commands ###
